spring.application.name=examen-dam1-tareas
server.port=8082

# Base de datos MySQL levantada con docker compose
spring.datasource.url=jdbc:mysql://localhost:3307/examen_dam1?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Madrid
spring.datasource.username=dam1
spring.datasource.password=dam1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracion JPA opcional. La base de datos ya existe; JPA no debe crear ni modificar tablas.
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Mensajes de error de Spring MVC algo mas utiles durante el desarrollo
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always